### ISSUE TITLE
resource sumologic_http_source doesn't support import

### ISSUE THREAD

**Issue by ss-remygreinhofer** [SumoLogic/sumologic-terraform-provider#45]
I am trying to import an existing http_source but when doing so, I get an error message from Terraform saying that the resource does not support import.

Here is the code for my `http_source`:

```hcl
resource "sumologic_http_source" "windows_performance_metrics" {
  name                = "Windows Performance"
  description         = ""
  message_per_request = "False"
  category            = "windows/performance"
  collector_id        = "185452687"
}
```

Following the example in the documentation I ran:

```bash
$ terraform import sumologic_http_collector.windows_performance_metrics 185452687/792423655
Error: resource address "sumologic_http_collector.windows_performance_metrics" does not exist in the configuration.

Before importing this resource, please create its configuration in the root module. For example:

resource "sumologic_http_collector" "windows_performance_metrics" {
  # (resource arguments)
}
```

It failed because the resource does not have the right type.

So assuming the documentation was incorrect, I ran:

```bash
$ terraform import sumologic_http_source.windows_performance_metrics 185452687/792423655
sumologic_http_source.windows_performance_metrics: Importing from ID "185452687/792423655"...

Error: sumologic_http_source.windows_performance_metrics (import id: 185452687/792423655): import sumologic_http_source.windows_performance_metrics (id: 185452687/792423655): resource sumologic_http_source doesn't support import
```

**Comment by bendrucker** [comment]
1. Typo, fixed in #46 
2. #40 is merged but not published in a release. You'd need to build from master if you want to use it this second. 

@frankreno Can you cut a new minor release soon?

**Comment by ss-remygreinhofer** [comment]
Thank you for your quick reply.

I rebuilt the provider from master (d1bcfd7), but I still see the same error when importing my resource.

**Comment by bendrucker** [comment]
Are you sure you moved it to the right place such that terraform is picking up the new provider? I was building from master and temporarily overriding the provider binary so that we could import some sources and then we reverted back to 0.2.1. 

https://www.terraform.io/docs/configuration/providers.html#plugin-names-and-versions

Try giving the binary a new version and using `terraform providers` to see that terraform is or isn't picking up the new binary

**Comment by ss-remygreinhofer** [comment]
My bad, it worked. I had to mess with the dependencies a little, otherwise it was using the latest stable.

```bash
$ terraform import sumologic_http_source.windows_performance_metrics 185452687/792423655
sumologic_http_source.windows_performance_metrics: Importing from ID "185452687/792423655"...
sumologic_http_source.windows_performance_metrics: Import complete!
  Imported sumologic_http_source (ID: 792423655)
sumologic_http_source.windows_performance_metrics: Refreshing state... (ID: 792423655)

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

**Comment by bendrucker** [comment]
Yup, `.terraform/plugins` wins over `$HOME/.terraform.d/plugins`. Can be tricky. You can also have multiple binaries and tell terraform which to use by picking a version AFAIK.
